### ISSUE TITLE
AssertionError while running app.py

### ISSUE THREAD

**Issue by Leandroscholz** [NeuBIAS/bise-core-ontology#12]
Hi @albangaignard , while trying to run the webapp I was not able to view the webapp due to some error. 

In order to run it on debug mode, I used the following commands: 
```
(bise-ld-webapp) $ export FLASK_ENV=development
(bise-ld-webapp) $ export FLASK_APP=app.py
(bise-ls-webapp) $ python -m flask run

```
After that, I have got the following messages. I don't know how to solve it. I am not sure if others had the same issue while running, but It might be important to fix it.  
```
Traceback (most recent call last):
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/__main__.py", line 14, in <module>
    main(as_module=True)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 894, in main
    cli.main(args=args, prog_name=name)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 557, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 767, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 293, in __init__
    self._load_unlocked()
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 317, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 372, in load_app
    app = locate_app(self, import_name, name)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/cli.py", line 235, in locate_app
    __import__(module_name)
  File "/home/leandro/Workspace/bise-core-ontology/bise-linked-data-webapp/app.py", line 61, in <module>
    @app.route('/')
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/app.py", line 1250, in decorator
    self.add_url_rule(rule, endpoint, f, **options)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/app.py", line 66, in wrapper_func
    return f(self, *args, **kwargs)
  File "/home/leandro/anaconda3/envs/bise-ld-webapp/lib/python3.6/site-packages/flask/app.py", line 1221, in add_url_rule
    'existing endpoint function: %s' % endpoint)
AssertionError: View function mapping is overwriting an existing endpoint function: index

```
![image](https://user-images.githubusercontent.com/29718327/45274804-6f929300-b48f-11e8-9540-04bbcea736e0.png)

**Comment by albangaignard** [comment]
Bug fixed, thanks for reporting !
